# PostgreSQL. Versions 9.3 and up are supported.
#
#
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  database: crafty_news_API_tech_interview_development

test:
  <<: *default
  username: postgres
  database: crafty_news_API_tech_interview_test

production:
  <<: *default
  database: crafty_news_API_tech_interview_production
  username: crafty_news_API_tech_interview
  password: <%= ENV['CRAFTY_NEWS_API_TECH_INTERVIEW_DATABASE_PASSWORD'] %>
